name: NNPD-CI

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run NNPD integration tests.
        run: |
          mkdir -p /home/runner/go/src/github.com/Roblox
          ln -s /home/runner/work/nomad-node-problem-detector/nomad-node-problem-detector /home/runner/go/src/github.com/Roblox/nomad-node-problem-detector
          cd /home/runner/go/src/github.com/Roblox/nomad-node-problem-detector/gha
          sudo ./setup.sh
          cd ..
          sudo make test
          nomad node status
